import XCTest
@testable import Togethr // ⚠️ REPLACE 'Togethr' WITH YOUR PROJECT NAME

final class TwentyQuestionsLogicTests: XCTestCase {

    // MARK: - 1. Data Model Tests
    // These ensure your basic data structures behave as expected (Equality, hashing, raw values).

    func testAnswerEnum() {
        // Test Raw Values ensuring they match what the View expects
        XCTAssertEqual(Answer.yes.rawValue, "yes")
        XCTAssertEqual(Answer.no.rawValue, "no")
        XCTAssertEqual(Answer.unknown.rawValue, "unknown")
        
        // Test CaseIterable (Implicitly generated by Swift, but good to verify count)
        XCTAssertEqual(Answer.allCases.count, 3)
    }
    
    func testRecordedQuestionStruct() {
        // Create sample data
        let id = UUID()
        let q1 = RecordedQuestion(id: id, questionText: "Is it alive?", answer: .yes)
        let q2 = RecordedQuestion(id: id, questionText: "Is it alive?", answer: .yes)
        let q3 = RecordedQuestion(questionText: "Is it blue?", answer: .no)
        
        // Test Equatable conformance
        XCTAssertEqual(q1, q2, "Two structs with same ID and content should be equal")
        XCTAssertNotEqual(q1, q3, "Structs with different content should not be equal")
        
        // Test Identifiable conformance
        XCTAssertEqual(q1.id, id)
    }

    // MARK: - 2. SecretInputViewModel Tests
    // These tests cover the placeholder logic and input validation.

    func testPlaceholderLogic() {
        // We test EVERY branch of the 'placeholderText' computed property to get 100% coverage.
        
        // Branch 1: Animals
        let vmAnimals = SecretInputViewModel(category: "Animals")
        XCTAssertEqual(vmAnimals.placeholderText, "e.g. Dolphin")
        
        // Branch 2: Food
        let vmFood = SecretInputViewModel(category: "Food")
        XCTAssertEqual(vmFood.placeholderText, "e.g. Pizza")
        
        // Branch 3: People
        let vmPeople = SecretInputViewModel(category: "Famous People")
        XCTAssertEqual(vmPeople.placeholderText, "e.g. Taylor Swift")
        
        // Branch 4: Movies
        let vmMovies = SecretInputViewModel(category: "Movies & TV")
        XCTAssertEqual(vmMovies.placeholderText, "e.g. Star Wars")
        
        // Branch 5: Objects
        let vmObjects = SecretInputViewModel(category: "Household Objects")
        XCTAssertEqual(vmObjects.placeholderText, "e.g. Toaster")
        
        // Branch 6: Places
        let vmPlaces = SecretInputViewModel(category: "Places")
        XCTAssertEqual(vmPlaces.placeholderText, "e.g. Paris")
        
        // Branch 7: Fallback (Concepts, etc.)
        let vmFallback = SecretInputViewModel(category: "Random Concepts")
        XCTAssertEqual(vmFallback.placeholderText, "e.g. Magic")
    }
    
    func testInputValidation() {
        let vm = SecretInputViewModel(category: "Animals")
        
        // Case A: Empty String (Invalid)
        vm.textInput = ""
        XCTAssertFalse(vm.isInputValid, "Empty input should be invalid")
        
        // Case B: Whitespace only (Invalid)
        vm.textInput = "   "
        XCTAssertFalse(vm.isInputValid, "Whitespace-only input should be invalid")
        
        // Case C: Newlines only (Invalid)
        vm.textInput = "\n"
        XCTAssertFalse(vm.isInputValid, "Newline-only input should be invalid")
        
        // Case D: Valid Text
        vm.textInput = "Tiger"
        XCTAssertTrue(vm.isInputValid, "Regular text should be valid")
    }

    // MARK: - 3. TwentyQuestionsGameViewModel Tests
    // These tests cover the gameplay loop, state management, and undo logic.

    func testGameInitialization() {
        let vm = TwentyQuestionsGameViewModel(category: "Space", secretWord: "Mars")
        
        XCTAssertEqual(vm.category, "Space")
        XCTAssertEqual(vm.secretWord, "Mars")
        XCTAssertTrue(vm.questionLog.isEmpty)
        XCTAssertEqual(vm.currentQuestionText, "")
        XCTAssertFalse(vm.questionAwaitingAnswer)
    }
    
    func testSubmitQuestion() {
        let vm = TwentyQuestionsGameViewModel(category: "Space", secretWord: "Mars")
        
        // 1. Submit valid question
        vm.submitQuestion("Is it red?")
        XCTAssertEqual(vm.currentQuestionText, "Is it red?")
        XCTAssertTrue(vm.questionAwaitingAnswer)
        
        // 2. Submit valid question with extra whitespace (Should trim)
        vm.cancelQuestion() // Reset first
        vm.submitQuestion("  Is it cold?  ")
        XCTAssertEqual(vm.currentQuestionText, "Is it cold?")
        XCTAssertTrue(vm.questionAwaitingAnswer)
        
        // 3. Submit empty/invalid (Should NOT update state)
        vm.cancelQuestion() // Reset first
        vm.submitQuestion("")
        XCTAssertEqual(vm.currentQuestionText, "")
        XCTAssertFalse(vm.questionAwaitingAnswer)
        
        // 4. Submit whitespace only (Should NOT update state)
        vm.submitQuestion("   ")
        XCTAssertEqual(vm.currentQuestionText, "")
        XCTAssertFalse(vm.questionAwaitingAnswer)
    }
    
    func testProvideAnswerFlow() {
        let vm = TwentyQuestionsGameViewModel(category: "Space", secretWord: "Mars")
        
        // Attempt to answer without a question pending (Guard Check)
        vm.provideAnswer(.yes)
        XCTAssertTrue(vm.questionLog.isEmpty, "Should not log answer if no question is pending")
        
        // Standard Flow
        vm.submitQuestion("Is it a planet?")
        vm.provideAnswer(.yes)
        
        XCTAssertEqual(vm.questionLog.count, 1)
        XCTAssertEqual(vm.questionLog.first?.questionText, "Is it a planet?")
        XCTAssertEqual(vm.questionLog.first?.answer, .yes)
        
        // Ensure state reset
        XCTAssertFalse(vm.questionAwaitingAnswer)
        XCTAssertEqual(vm.currentQuestionText, "")
    }
    
    func testCancelQuestion() {
        let vm = TwentyQuestionsGameViewModel(category: "Space", secretWord: "Mars")
        
        // Setup a pending question
        vm.submitQuestion("Mistake Question")
        XCTAssertTrue(vm.questionAwaitingAnswer)
        
        // Act
        vm.cancelQuestion()
        
        // Assert
        XCTAssertFalse(vm.questionAwaitingAnswer)
        XCTAssertEqual(vm.currentQuestionText, "")
        XCTAssertTrue(vm.questionLog.isEmpty, "Canceling should not add to the log")
    }
    
    func testUndoLastLog() {
        let vm = TwentyQuestionsGameViewModel(category: "Space", secretWord: "Mars")
        
        // 1. Undo on empty (Guard Check)
        vm.undoLastLog()
        XCTAssertTrue(vm.questionLog.isEmpty, "Undo on empty log should be safe")
        
        // 2. Undo with items
        vm.submitQuestion("Q1")
        vm.provideAnswer(.yes)
        vm.submitQuestion("Q2")
        vm.provideAnswer(.no)
        
        XCTAssertEqual(vm.questionLog.count, 2)
        
        // Perform Undo
        vm.undoLastLog()
        
        XCTAssertEqual(vm.questionLog.count, 1)
        XCTAssertEqual(vm.questionLog.first?.questionText, "Q1", "Should leave the first question intact")
        
        // Verify state is clean
        XCTAssertFalse(vm.questionAwaitingAnswer)
        XCTAssertEqual(vm.currentQuestionText, "")
    }
}
